name: Cypress Test

on:
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run # Replace with your test script command

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results

      - name: Set GITHUB_TOKEN
        run: echo "export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV